@SuperDotnet_HostAddress = http://localhost:9999

POST {{SuperDotnet_HostAddress}}/fraud-score
Content-Type: application/json
Accept: application/json

{
	"id": "tx_001",
	"transaction": {
		"amount": 199000.9,
		"installments": 3,
		"requested_at": "2026-05-10T12:34:56Z"
	},
	"customer": {
		"avg_amount": 120.5,
		"tx_count_24h": 12,
		"known_merchants": [
			"m_01",
			"m_02"
		]
	},
	"merchant": {
		"id": "m_03",
		"mcc": "5411",
		"avg_amount": 150000.0
	},
	"terminal": {
		"is_online": true,
		"card_present": false,
		"km_from_home": 12.4
	},
	"last_transaction": {
		"timestamp": "2026-05-09T20:15:00Z",
		"km_from_current": 2.1
	}
}

###

GET {{SuperDotnet_HostAddress}}/ready
Accept: application/json

###
GET {{SuperDotnet_HostAddress}}/random-vector
###
GET {{SuperDotnet_HostAddress}}/search/7658