@SuperDotnet_HostAddress = http://localhost:9999

GET {{SuperDotnet_HostAddress}}/fraud-score
Accept: application/json

###

GET {{SuperDotnet_HostAddress}}/ready
Accept: application/json

###
GET {{SuperDotnet_HostAddress}}/random-vector
###
GET {{SuperDotnet_HostAddress}}/search/25